### ISSUE TITLE
question: gen from GRPC 

### ISSUE THREAD

**Issue by joeblew99** [myitcv/g#24]
looks good.

i want to generate from GRPC out to files in order to build a basic Computation Flow Graph.
So i basically need to be able to get at the types and their relationships.

just wondering if this is similar to some of your use cases for building this and if you think its a decent match

**Comment by myitcv** [comment]
@joeblew99 

> looks good.

> I want to generate....

Can you confirm what you're referring to here?

**Comment by joeblew99** [comment]
well i noticed your dong AST on the PBs. 
What i am playing with is the the idea of using GRPC as we all do, but parsing that IDL, and code generating lots of other stuff.

For example if you have a data storage layer you want to map the GRPC to the data storage layer. Thats a simplistic example, but just to get the idea across.
I can provide more info, but i think this gets the point across ?

So, i am wondering if this is the intent of this repo ?

**Comment by myitcv** [comment]
Ah so you're referring to the packages `github.com/myitcv/g/protobuf/...` (as opposed to the commands under `github.com/myitcv/g/cmd/...`)

Yes, the AST work was forked from original work by David Symonds.

We do a fair amount of work that relies on parsing ASTs from proto files:

* vetting and linting of proto files (in the spirit of `go vet` and `golint`)
* formatting of proto files (in the spirit of `gofmt`)
* generate proto files from proto files (in the spirit of `go generate`)
* generating Go (and other language) code based on proto files, essentially code generation beyond (and in some cases to replace) the code that would otherwise be generated via `protoc`

So yes, the basic parsing and AST packages serve as the basis for a number of other, current non-public, commands that work with proto files in one way or another.

Does that help to clarify?

**Comment by myitcv** [comment]
@joeblew99 closing this issue for now. 

Please raise a new issue at my new mono repo via https://github.com/myitcv/x/issues/new?title=protobuf: in case you would like to continue the discussion!
